added condition if pylint failed

diff --git a/.github/workflows/docker-ci.yml b/.github/workflows/docker-ci.yml
--- a/.github/workflows/docker-ci.yml
+++ b/.github/workflows/docker-ci.yml
@@ -45,13 +45,10 @@ jobs:
         run: docker-compose down
 
       - name: Check if Pylint testing was Successful
+        if: steps.pylint.outputs.pylint_success != 'true'
         run: |
-          if steps.pylint.outputs.pylint_success == 'true'; then
-            echo "Pylint test run successfully."
-          else
-            echo "Pylint test run failed."
-            exit 1 
-          fi
+          echo "Pylint test run failed."
+          exit 1
 
       - name: Check Pylint Report
         run: |
