fixed docker-ci bug

diff --git a/.github/workflows/docker-ci.yml b/.github/workflows/docker-ci.yml
--- a/.github/workflows/docker-ci.yml
+++ b/.github/workflows/docker-ci.yml
@@ -45,13 +45,12 @@ jobs:
         run: docker-compose down
 
       - name: Check if Pylint testing was Successful
-        - name: Check if Pylint testing was Successful
-          if: steps.pylint.outputs.pylint_success == 'true'
-          run: |
-            echo "Pylint test run successfully."
-          else
-            echo "Pylint test run failed."
-            exit 1
+        if: steps.pylint.outputs.pylint_success == 'true'
+        run: |
+          echo "Pylint test run successfully."
+        else
+          echo "Pylint test run failed."
+          exit 1
 
       - name: Check Pylint Report
         run: |
